{% set version = "8.8.0" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: ijar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 71cea4e6df77d5d85e185db7f238d96db50132bf40c94e4978a35d92eaf42108

  - fn: bazel
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 4b6a8be4bf1f1f3aac05a0b7ebccfe3c3f12ce6ddb4bdc6593904b9f872a5c3d  # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-arm64   # [build_platform == "linux-aarch64"]
    sha256: 0490da39cd9de866eb79790accd2df260e4cc86167c84457cc1a702d4058361f  # [build_platform == "linux-aarch64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 795865814cfa6fed8d54350ada5d9a3e865b8441927092a004142fc7ef67d357  # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2.0,<0.5.0
    - openjdk
    - sed

test:
  commands:
    - test -f $PREFIX/bin/ijar
    - test -f $PREFIX/bin/zipper

about:
  home: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  dev_url: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  license: Apache-2.0
  license_family: MIT
  license_file: third_party/ijar/LICENSE
  summary: A tool for generating interface .jars from normal .jars
  description: A tool for generating interface .jars from normal .jars

extra:
  skip-lints:
    - missing_documentation
    - missing_hash
    - missing_source
  recipe-maintainers:
    - xhochy
    - conda-forge/bazel
